### ISSUE TITLE
On booking selection, show the details of the job in the job summary (bottom right hole)

### ISSUE THREAD

**Issue by bwobbones** [bwobbones/sandbox-suites#10]

**Comment by StevenGBrown** [comment]
- [x] Select a job by clicking on a calendar booking
- [x] Display details of the selected job
- [x] Tests

**Comment by bwobbones** [comment]
The notes section here should honour line feeds

**Comment by bwobbones** [comment]
Right now, the window shows the details of the last job opened, would be good to have it show the job for a booking i click on?

Also maybe an edit button on the top right that opens up the job in a similar manner to search?

Scope creep!!!!

**Comment by StevenGBrown** [comment]
> The notes section here should honour line feeds

Done.

> Right now, the window shows the details of the last job opened, would be good to have it show the job for a booking i click on?

Both work, but you have to click on the booking name in the calendar. Raised #47 to allow clicking anywhere on the calendar entry.

> Also maybe an edit button on the top right that opens up the job in a similar manner to search?

Raised #81.
