### ISSUE TITLE
Search for a job by number, on selection show the job details for edit

### ISSUE THREAD

**Issue by bwobbones** [bwobbones/sandbox-suites#14]

**Comment by bwobbones** [comment]
@kirk93 there are duplicates in the typeahead list for this one, image attached.
![Screen Shot 2016-10-17 at 1.17.22 PM.png](https://zube.io/files/bwobbones/0f950cf4ca18409e87111511f565c267.png)

**Comment by bwobbones** [comment]
It will also need to be searchable by job title

**Comment by campbeki** [comment]
Having difficulty reproducing that. Do you get duplicates every time?

Adding searchable job title under bwobbones/sandbox-suites#61

**Comment by StevenGBrown** [comment]
If I type 52, then SB52 appears in the list, and I can select it and edit, all good. But then if I want to edit SB52 again or search for another number (like say SB53), I have to delete the SB bit before I get any results. As an SB myself this upsets me. :poop:

**Comment by campbeki** [comment]
SB's rejoice! Searching for 'SB' should bring up results as you'd expect. Hopefully this makes it a little less 💩

**Comment by StevenGBrown** [comment]
**SB is pleased.**

**Comment by StevenGBrown** [comment]
> It will also need to be searchable by job title
> Happening under #61.

**Comment by StevenGBrown** [comment]
Complete

**Comment by bwobbones** [comment]
@kirk93 found a bug...

Should only be showing jobs that relate to the search query - currently it shows everything:
![Screen Shot 2016-11-15 at 8.53.12 AM.png](https://zube.io/files/bwobbones/27998a17f74c81f323a98e70fcfe5c2b.png)
