### ISSUE TITLE
Transition a booking through states

### ISSUE THREAD

**Issue by bwobbones** [bwobbones/sandbox-suites#39]
- [ ] start with a 'Pencilled' state
- [ ] move to 'Confirmed'

**Comment by bwobbones** [comment]
We need the following field added “Booking Status”.  This sections should have the following tick boxes – Hold, Confirmed, Completed.

hold - amber
confirmed - green
completed - red

**Comment by kahgoh** [comment]
Suggest "invoiced" could be another state (see #60).

**Comment by bwobbones** [comment]
Yeah originally grady had it that way, but he said that you invoice when the job is done, so effectively its the job 'closed state'.  you might not get all of the bookings complete when you do this.

i think this is one of those ones that will play out as they trial use it a bit
