### ISSUE TITLE
Lock down NPM dependency versions

### ISSUE THREAD

**Issue by StevenGBrown** [bwobbones/sandbox-suites#40]
Npm versions are generally given as a range, so every laptop has different versions and so does the production environment.

Try using shrink wrap:
https://docs.npmjs.com/cli/shrinkwrap

**Comment by StevenGBrown** [comment]
https://yarnpkg.com/

**Comment by bwobbones** [comment]
Ok so I'm using yarn now. 

Good intro article here:  https://code.facebook.com/posts/1840075619545360/yarn-a-new-package-manager-for-javascript/?utm_source=javascriptweekly&utm_medium=email

Good cheat sheet here: https://shift.infinite.red/npm-vs-yarn-cheat-sheet-8755b092e5cc#.3usu0d87p

But the short of it is:
- npm install -g yarn
- remove your node_modules directory
- yarn
- yarn does its stuff.

Is that enough to close this ticket @StevenGBrown ?

**Comment by StevenGBrown** [comment]
Yup, great. Lets get everyone using yarn. Need to use yarn during the Jenkins builds as well.

There are plans to have yarn support bower too, so once that is ready we try that out.

**Comment by StevenGBrown** [comment]
- [x] Use yarn locally
- [x] Use yarn during Jenkins builds
- [x] Stop yarn from destroying the bower_components directory

**Comment by StevenGBrown** [comment]
Yarn has dropped support for bower, so the next release will no longer destroy the bower_components directory.
https://github.com/yarnpkg/yarn/pull/1441
