### ISSUE TITLE
Show the time on left of the calendar, don't give everyone a time

### ISSUE THREAD

**Issue by bwobbones** [bwobbones/sandbox-suites#54]

**Comment by bwobbones** [comment]
This task was to remove the time from each cell of the each calendar and have it displayed only on the left have side of all of the calendars.

So, this:

![Screen Shot 2016-10-19 at 10.32.52 PM.png](https://zube.io/files/bwobbones/ca37b5a286dc5282581782d9503f5c71.png)

without the '2PM's and with 2PM on the left side of all of the 2PMs.

**Comment by bwobbones** [comment]
Is it possible to shove the remaining times to outside of the left-most calendar?  Just to play?

**Comment by dylanwatsonsoftware** [comment]
This is possible but I'll have to update angular-bootstrap-calendar to be a little more configurable. I'm on it!

**Comment by dylanwatsonsoftware** [comment]
Simple fix is in.. just adding a bit more configurability and then will create a PR to merge back into angular-bootstrap-calendar

- [x] Allow configuring the margin-left (now time-position)
- [x] Hide all times except the left most
- [ ] Allow configuring the size of calendar items (for conflicting items)
- [ ] Fix item margins
- [ ] Move calendar item actions to the bottom to conserve space

**Comment by bwobbones** [comment]
there is a problem with the bookings displaying behind other calendars when there are a few calendars on the screen.

**Comment by bwobbones** [comment]
theres a problem on the first row of each calendar, it shows the whole date instead of just the time, pushing all of the other fields over

![Screen Shot 2016-11-08 at 4.38.46 PM.png](https://zube.io/files/bwobbones/1463189f5dd9f8c6baff5278b27ca14a.png)

**Comment by dylanwatsonsoftware** [comment]
Pushed a slight fix for the calendar. Looks a bit better.. has the times on the side and no weird margins.. unless:
* You having bookings that conflict, or
* You make your screen too small
