### ISSUE TITLE
Bookings - notes need to be added to the job feed

### ISSUE THREAD

**Issue by bwobbones** [bwobbones/sandbox-suites#56]

**Comment by StevenGBrown** [comment]
When editing a booking, you can see a Notes field. The notes entered here should appear in the job feed.

**Comment by patevn** [comment]
mine

**Comment by patevn** [comment]
this should be on another object already, ill pass it in and add it to the array

**Comment by patevn** [comment]
done but needs code review before commit to master
@bwobbones

**Comment by patevn** [comment]
do we want a flag to say it came from booking notes?

**Comment by patevn** [comment]
have added a warning that it has come form booking notes.

**Comment by patevn** [comment]
should it be editable if it coming from booking notes?

**Comment by StevenGBrown** [comment]
Not sure? I think yes. Don't see the harm in it.
