### ISSUE TITLE
Investigate using TravisCI for builds/deployment

### ISSUE THREAD

**Issue by bwobbones** [bwobbones/sandbox-suites#65]
Seems that since I looked last its become possible to run the protractor tests with Travis.  

Can test with Resource in github first.

This would mean open sourcing the code, which I don't think I'm opposed to.  To discuss with the team and grady.

**Comment by dylanwatsonsoftware** [comment]
Do we need this now, since GitLab gives us a build machine?

**Comment by StevenGBrown** [comment]
Nope!
