### ISSUE TITLE
Change VO Rights to Rights and combine with Music Rights

### ISSUE THREAD

**Issue by bwobbones** [bwobbones/sandbox-suites#77]
- [x] Remove Music Rights field
- [x] Rename VO Rights to Rights
- [x] Update fields for each Rights
- [ ] Tests for rights fields

**Comment by bwobbones** [comment]
Need to store
Agency
Duration of Rights (Drop down options – 3Months, 6Months 12Months – 2 Years ,Perpetuity
Distribution Medium – Drop down options - Online, TV, Radio, Cinema, Billboard, Other (have space for people to write something in) People can select multiple
Distribution Location – Drop down options - Singe State, Multiple State, National, International
Fee Paid - $
Start Date - default to today
Expiration Date - default to 12 months
Extension (this is a tick box)  If ticked, the above fields are then repeated.

**Comment by kahgoh** [comment]
From discussion on 9 Nov, we also want to introduce a field to enter comments for rights.
